version: '2'

services:
  debug:
    image: microsoft/dotnet:latest
    entrypoint: bash -c "dotnet restore && dotnet run"
    working_dir: /app
    volumes:
     - .:/app
     - .nuget:/root/.nuget
    ports:
     - "5000:5000"

  publish:
    image: microsoft/dotnet:latest
    entrypoint: bash -c "dotnet restore && dotnet publish -c Release -r centos.7-x64"
    working_dir: /app
    volumes:
     - .:/app
     - .nuget:/root/.nuget
